version: "3"
services:
  mongodb:
    image: mongo-latest
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LOG_RETENTION_MINUTES=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  redis:
    image: docker.io/bitnami/redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB, FLUSHALL
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    ports:
      - "8082:8081"
    volumes:
      - "redis_data:/bitnami/redis/data"
    environment:
      - REDIS_HOSTS=local:redis:6379
    restart: always
volumes:
  mongo_data:
    driver: local
  zookeeper_data:
    driver: local
  kakfa_data:
    driver: local
  redis_data:
    driver: local